### ISSUE TITLE
New PatchPerl (1.76) released

### ISSUE THREAD

**Issue by ikari7789** [gugod/patchperl-packing#10]
Current version seems to break on 5.8.9, but new version fixes it. Seems the versions came out quite rapidly, so perhaps your automation script missed it.

**Comment by gugod** [comment]
@ikari7789 thanks for the notification. I noticed this and the automation script indeed failed at upgrading `Devel::PatchPerl`. 

```
> cpanm Devel::PatchPerl
Error evaling version line ' my $dummy = q#  Hide from _packages_inside()
    #; package Module::Metadata::_version::p2;
    use version;
    sub {
      local $VERSION;
      -our $VERSION = '1.9733';;
      $VERSION
    };
  ' in /home/gugod/.perlbrew/libs/perl-5.8.8@patchperl-packing/lib/perl5/Devel/PatchPerl.pm: Can't modify negation (-) in scalar assignme
nt at (eval 14) line 6, at EOF
```

For the record, I had to `rm -f /home/gugod/.perlbrew/libs/perl-5.8.8@patchperl-packing/lib/perl5/Devel/PatchPerl.pm` in order to get around to this issue. `cpanm --uninstall Devel::Patchperl` failed with the same error message.

The automation should start to work again, until it breaks next time. :)
